---
- hosts: localhost
  become: yes
  gather_facts: True

  ...
  collections:
    - servicenow.itsm
...
  tasks:
    - incident_info:
        instance:
          host: https://dev12345.service-now.com
          username: user
          password: pass
        number: INC0000039
      register: result

- name: Create change request
  servicenow.itsm.change_request:
    instance:
      host: https://dev336605.service-now.com
      username: aes.creator
      password: xFWb%1a*c6UO

    type: standard
    state: new
    requested_by: some.user
    short_description: Install new Cisco Super Duper Shmooper
    description: Please install new Cat. 6500 in Data center 01
    attachments:
      - path: path/to/attachment.txt
    priority: moderate
    risk: low
    impact: low

    other:
      expected_start: 2021-02-12

- name: Change state of the change request
  servicenow.itsm.change_request:
    instance:
      host: https://dev336605.service-now.com
      username: aes.creator
      password: xFWb%1a*c6UO

    state: assess
    assignment_group: some.group
    number: CHG0000001

- name: Close change_request
  servicenow.itsm.change_request:
    instance:
      host: https://dev336605.service-now.com
      username: aes.creator
      password: xFWb%1a*c6UO

    state: closed
    close_code: "successful"
    close_notes: "Closed"
    assignment_group: some.group
    number: CHG0000001

- name: Delete change_request
  servicenow.itsm.change_request:
    instance:
      host: https://dev336605.service-now.com
      username: aes.creator
      password: xFWb%1a*c6UO

    state: absent
    number: CHG0000001


  

  





