---
    - name: RFRSH2025Q2 Omni-Client PROD_2_UAT | announce oracle_schema_refresh
      hosts: localhost
      gather_facts: true
      vars_files:
        - vars/main.yml

      tasks:

      - name: Auto-Create "RFRSH2025Q2 Omni-Client PROD_2_UAT" Task in ServiceNow | itsm_oracle_refresh_wrapper
        servicenow.itsm.incident:
          instance:
            host: "{{ sn_instance}}"
            username: "{{ sn_username }}"
            password:  "{{ sn_password }}"
          close_code: 003
          state: open
            # No sys_id or number because we are creating a new incident
            # Common parameters
          caller: admin
          short_description: Refresh All UAT Databases from PROD
          impact: low
          urgency: medium
          other:
            problem_id: 00011
        register: refresh_new_inc_out

      - debug:
          msg: Ansible Starting the Quarterly RFRSH2025Q2 Omni-Client PROD_2_UAT | itsm_oracle_refresh_wrapper

      - name: Change ServiceNow Refresh Task State to In-Progress | prepare oracle_schema_refresh
        servicenow.itsm.incident:
          instance:
            host: "{{ sn_instance}}"
            username: "{{ sn_username }}"
            password:  "{{ sn_password }}"
          sys_id: "{{ refresh_new_inc_out.record.sys_id }}"
          state: in_progress

      - debug:
          msg: Ansible Verified & Opened an Oracle RFRSH2025Q2 Omni-Client PROD_2_UAT Task {{ refresh_new_inc_out.record.task_effective_number }} in ServiceNow | itsm_oracle_refresh_wrapper
       
      - name: Prepare Oracle Refresh Process | execute oracle_schema_refresh
        servicenow.itsm.incident_info:
          instance:
            host: "{{ sn_instance}}"
            username: "{{ sn_username }}"
            password:  "{{ sn_password }}"
          sys_id: "{{ refresh_new_inc_out.record.sys_id }}"
        register: refresh_execute_out

      - debug:
          msg: Ansible Executing RFRSH2025Q2 Omni-Client PROD_2_UAT Task {{ refresh_new_inc_out.record.task_effective_number }} | itsm_oracle_refresh_wrapper

      - name: Cache the Refresh Task SYS_ID for All Playbooks to Re-Use | prepare oracle_database_refresh
        ansible.builtin.set_fact:
          sys_id: "{{ refresh_new_inc_out.record.sys_id }}"
          cacheable: yes

      - name: Write the Refresh Task SYS_ID Variable to the Disk on CTRL+ Node Alone | itsm_oracle_refresh_wrapper
        copy:
          content: "{{ refresh_new_inc_out.record.sys_id }}"
          dest: "/tmp/refresh_task_sid.txt"
        delegate_to: localhost

    - import_playbook: itsm_oracle_refresh_actual_prod.yml
    - import_playbook: itsm_oracle_refresh_actual_dev.yml
    - import_playbook: itsm_oracle_refresh_actual_uat.yml
    - import_playbook: itsm_oracle_refresh_actual_cert.yml
    - import_playbook: itsm_oracle_refresh_finish.yml   


