---
    - name: RFRSH-2025-Q3 Omni-Client PROD_2_PREPROD-UAT-DEV TemplCAB-Pre-Approved V1.3.Draft | announce oracle_schema_refresh_completion
      hosts: localhost
      gather_facts: true
      vars_files:
        - vars/main.yml

      tasks:
     
        - debug:
            msg: Ansible is Closing the Omni-Client Refresh Task as Successful 

        - name: Close ServiceNow Refresh Task as Completed | itsm_oracle_refresh_finish
          servicenow.itsm.incident:
            instance:
              host: "{{ sn_instance}}"
              username: "{{ sn_username }}"
              password:  "{{ sn_password }}"
            sys_id:  "{{ lookup('ansible.builtin.file', '/tmp/refresh_task_sid.txt') }}"
            state: closed
            close_code: "2025Q5 Refreshed (Omni-CLient UAT)"
            close_notes: "Closed"
          register: closing_notes_out

        - debug:
            msg: Ansible is Entering the Following in the Closing Notes for the Current Iteration of RFRSH-2025-Q3 Omni-Client PROD_2_PREPROD-UAT-DEV TemplCAB-Pre-Approved V1.3.Draft | itsm_oracle_refresh_finish

        - debug: var=closing_notes_out
         
        - name: Cleanup the Temp Refresh Files | itsm_oracle_refresh_finish
          ansible.builtin.file:
            path: /tmp/refresh_task_sid.txt
            state: absent
          delegate_to: localhost
          ignore_errors: True

        - debug:
            msg: Ansible Has Flashed the Neuralizer Memory Erazer Thingy to Purge the Task SYS_ID from Memory + Disk | itsm_oracle_refresh_finish

        - debug:
            msg: Ansible Has Now Closed the FRSH-2025-Q3 Omni-Client PROD_2_PREPROD-UAT-DEV TemplCAB-Pre-Approved V1.3.Draft Task as Successful. Thank You and Have a Nice Day.
          
       
